// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PPB.DAL;

namespace PPB.DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210303200828_test22")]
    partial class test22
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("PPB.DAL.Concrete.BattleLogs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("LobbyNo")
                        .HasColumnType("text");

                    b.Property<string>("PlayerMove")
                        .HasColumnType("text");

                    b.Property<int>("RoundNo")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<int>("roundScore")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("BattleLogs", "PPB");
                });

            modelBuilder.Entity("PPB.DAL.Concrete.Musics", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.HasKey("_id");

                    b.ToTable("Musics", "PPB");
                });

            modelBuilder.Entity("PPB.DAL.Concrete.PlayerLobby", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("LobbyNo")
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("PlayerLobby", "PPB");
                });

            modelBuilder.Entity("PPB.DAL.Concrete.UserMusics", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("MusicID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("_id");

                    b.ToTable("UserMusics", "PPB");
                });

            modelBuilder.Entity("PPB.DAL.Concrete.Users", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("Coin")
                        .HasColumnType("integer");

                    b.Property<string>("NameSurname")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("boolean");

                    b.HasKey("UserID");

                    b.ToTable("Users", "PPB");
                });
#pragma warning restore 612, 618
        }
    }
}
